# template_asr_third/src/configs/transforms/instance_transforms/example.yaml

train:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000

  audio:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
        min_gain_in_db: -2.0
        max_gain_in_db: 2.0
        p: 0.2
      - _target_: src.transforms.wav_augs.add_colored_noise.AddColoredNoiseWrap
        p: 0.2
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.pitch_shift.PitchShift
        min_transpose_semitones: -2.0
        max_transpose_semitones: 2.0
        p: 0.2
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.time_stretch.TimeStretch
        min_rate: 0.9
        max_rate: 1.1
        p: 0.2
        sample_rate: 16000

  spectrogram:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchaudio.transforms.FrequencyMasking
        freq_mask_param: 8
        iid_masks: False
      - _target_: torchaudio.transforms.TimeMasking
        time_mask_param: 15
        iid_masks: False

inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
